// =============================================================================
// Module  : compute_layer
// Purpose : Dilithium verification compute block
//
// Flow:
//   1. Load w_prime[256] from ROM (w_prime.hex)
//   2. Feed each 23-bit coeff into decompose → r1 (high bits = w1')
//   3. XOR-accumulate (r1 & 0xFF) across all 256 coeffs → checksum
//   4. XOR checksum with mu[0] → result
//   5. Compare result vs c_tilde[0] from received packet
//   6. Assert valid=1 (GREEN) or valid=0 (RED)
//
// Port notes:
//   start      : pulse from pkt_valid (Block 1 output)
//   c_tilde_0  : sig[0] extracted by packet_receiver
//   mu_0       : mu[0] from mu.hex (hardcoded or loaded)
//   done       : 1-cycle pulse when result ready
//   valid      : 1 = GREEN, 0 = RED
// =============================================================================
 `timescale 1ns/1ps


module compute_layer (
    input  wire       clk,
    input  wire       rst,
    input  wire       start,
    input  wire [7:0] c_tilde_0,  // sig[0] from packet
    input  wire [7:0] mu_0,        // mu[0] from SHAKE-256 of message
    output reg        done,
    output reg        valid
);
 
    // -------------------------------------------------------------------------
    // w_prime ROM — 256 coefficients, 23-bit each
    // Generated by Python script (w_prime.hex), seed=42
    // -------------------------------------------------------------------------
    reg [22:0] w_prime [0:255];
    initial $readmemh("w_prime.hex", w_prime);
 
    // -------------------------------------------------------------------------
    // Decompose instance — combinational
    // Input:  [45:0] r  (zero-extend 23-bit coeff to 46 bits)
    // Output: [5:0]  r1 (high bits = w1' contribution)
    //         [18:0] r0 (not used here)
    // gamma_sel = 0 for ML-DSA-44 (gamma2 = 95232)
    // -------------------------------------------------------------------------
    reg  [22:0] coeff_in;
    wire [45:0] coeff_ext = {23'b0, coeff_in};
    wire [5:0]  dec_r1;
    wire [18:0] dec_r0;
 
    decompose u_decompose (
        .r         (coeff_ext),
        .gamma_sel (1'b0),
        .r1        (dec_r1),
        .r0        (dec_r0)
    );
 
    // -------------------------------------------------------------------------
    // FSM
    // -------------------------------------------------------------------------
    localparam S_IDLE    = 3'd0;
    localparam S_RUN     = 3'd1;
    localparam S_COMPARE = 3'd2;
    localparam S_DRAIN   = 3'd3;


 
    reg [2:0]  state   = S_IDLE;
    reg [7:0]  cnt     = 0;       // 0..255
    reg [7:0]  xor_acc = 0;       // XOR accumulator
 
    always @(posedge clk) begin
        if (rst) begin
            state   <= S_IDLE;
            cnt     <= 0;
            xor_acc <= 0;
            done    <= 0;
            valid   <= 0;
        end else begin
            done <= 0; // default
 
            case (state)
 
                S_IDLE: begin
                    if (start) begin
                        cnt     <= 0;
                        xor_acc <= 0;
                        state   <= S_RUN;
                    end
                end
 
                S_RUN: begin
                    // Feed current coefficient to decompose (combinational)
                    coeff_in <= w_prime[cnt];  // loads this cycle
    
                // dec_r1 reflects w_prime[cnt-1] due to register delay
                // Only accumulate after first cycle
                    if (cnt > 0)
                        xor_acc <= xor_acc ^ (dec_r1 & 8'hFF);

                    if (cnt == 8'd255)
                        state <= S_DRAIN;  // add drain state
                    else
                        cnt <= cnt + 1;
                end
 
                S_COMPARE: begin
                    // result = checksum ^ mu[0]
                    // compare against c_tilde[0]
                    valid <= ((xor_acc ^ mu_0) == c_tilde_0);
                    done  <= 1;
                    state <= S_IDLE;
                end

                S_DRAIN: begin
                    // capture last coefficient's r1
                    xor_acc <= xor_acc ^ (dec_r1 & 8'hFF);
                    state   <= S_COMPARE;
                end

                
 
                default: state <= S_IDLE;
 
            endcase
        end
    end
 
endmodule